version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    restart: always
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles  # 🔹 Compartir archivos estáticos
      - media_volume:/code/media  # 🔹 Compartir archivos de media (opcional)
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./core/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # 🔹 Configuración de Nginx
      - static_volume:/code/staticfiles  # 🔹 Servir archivos estáticos
      - media_volume:/code/media  # 🔹 Servir archivos de media (opcional)
    depends_on:
      - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin_data:

