# Generated by Django 5.1.7 on 2025-03-22 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtarea',
            name='campo_modificado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='detalles_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='tipo_cambio',
            field=models.CharField(choices=[('creacion', 'Creación de tarea'), ('edicion', 'Edición de tarea'), ('cambio_estado', 'Cambio de estado'), ('cambio_progreso', 'Cambio de progreso'), ('asignacion', 'Asignación de usuario'), ('cambio_departamento', 'Cambio de departamento'), ('completada', 'Tarea completada'), ('cancelada', 'Tarea cancelada'), ('sistema', 'Cambio del sistema')], default='sistema', max_length=20),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='valor_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='valor_nuevo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='ultima_modificacion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialtarea',
            name='accion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
