# Generated by Django 5.1.7 on 2025-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_historialtarea_campo_modificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialtarea',
            name='campo_modificado',
        ),
        migrations.RemoveField(
            model_name='historialtarea',
            name='detalles_adicionales',
        ),
        migrations.RemoveField(
            model_name='historialtarea',
            name='tipo_cambio',
        ),
        migrations.RemoveField(
            model_name='historialtarea',
            name='valor_anterior',
        ),
        migrations.RemoveField(
            model_name='historialtarea',
            name='valor_nuevo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='ultima_modificacion',
        ),
        migrations.AlterField(
            model_name='historialtarea',
            name='accion',
            field=models.TextField(default='Acción no especificada'),
            preserve_default=False,
        ),
    ]
