# Generated by Django 5.1.7 on 2025-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_historialtarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
