# Generated by Django 5.1.7 on 2025-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_options_customuser_ultimo_ingreso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='password_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña de correo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='puerto_entrante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puerto IMAP'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='puerto_saliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Puerto SMTP'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='servidor_entrante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Servidor IMAP'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='servidor_saliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Servidor SMTP'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='tiene_bandeja',
            field=models.BooleanField(default=False, verbose_name='¿Tiene bandeja de entrada?'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='usar_tls',
            field=models.BooleanField(default=True, verbose_name='Usar TLS'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuario_correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Usuario de correo'),
        ),
    ]
