# Generated by Django 4.2.7 on 2025-03-23 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='departamentos_acceso',
            field=models.ManyToManyField(blank=True, related_name='usuarios_con_acceso', to='usuarios.departamento'),
        ),
        migrations.CreateModel(
            name='UsuarioPrivilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento')),
                ('privilegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.privilegio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'privilegio', 'departamento')},
            },
        ),
    ]
