# Generated by Django 4.2.7 on 2025-03-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_privilegio_customuser_departamentos_acceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='departamento',
        ),
    ]
