# Generated by Django 4.2.7 on 2025-03-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_customuser_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioprivilegio',
            options={'verbose_name': 'Privilegio de Usuario', 'verbose_name_plural': 'Privilegios de Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuarioprivilegio',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilegios_usuarios', to='usuarios.departamento'),
        ),
    ]
